/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { callMcpTool } from '@magsag/mcp-client';

/**
 * append_note arguments
 */
export type AppendNoteArgs = {
  /**
   * Path to the Obsidian note relative to the vault root.
   */
  path: string;
  /**
   * Markdown payload to append.
   */
  content: string;
  /**
   * Create the note if it is missing.
   */
  create_if_missing?: boolean;
};

/**
 * append_note result
 */
export type AppendNoteResult = {
  [key: string]: unknown;
};

/**
 * Append Markdown content to a note.
 * Appends Markdown to the target file, optionally creating the note when it does not exist.
 */
export const appendNote = callMcpTool<AppendNoteArgs, AppendNoteResult>({
  serverId: "obsidian",
  toolName: "append_note",
  summary: "Append Markdown content to a note.",
  description: "Appends Markdown to the target file, optionally creating the note when it does not exist.",
  inputSchema: {
  "type": "object",
  "required": [
    "path",
    "content"
  ],
  "properties": {
    "path": {
      "type": "string",
      "description": "Path to the Obsidian note relative to the vault root."
    },
    "content": {
      "type": "string",
      "description": "Markdown payload to append."
    },
    "create_if_missing": {
      "type": "boolean",
      "description": "Create the note if it is missing."
    }
  }
} as const,
  outputSchema: {
  "type": "object",
  "description": "Operation metadata supplied by the Obsidian MCP server.",
  "additionalProperties": true
} as const,
});
