/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { callMcpTool } from '@magsag/mcp-client';

/**
 * retrieve_page arguments
 */
export type RetrievePageArgs = {
  /**
   * Notion page identifier.
   */
  page_id: string;
  /**
   * When true, include child blocks recursively.
   */
  include_children?: boolean;
};

/**
 * retrieve_page result
 */
export type RetrievePageResult = {
  [key: string]: unknown;
};

/**
 * Retrieve a Notion page by id.
 * Fetches metadata and block content for the requested Notion page.
 */
export const retrievePage = callMcpTool<RetrievePageArgs, RetrievePageResult>({
  serverId: "notion",
  toolName: "retrieve_page",
  summary: "Retrieve a Notion page by id.",
  description: "Fetches metadata and block content for the requested Notion page.",
  inputSchema: {
  "type": "object",
  "required": [
    "page_id"
  ],
  "properties": {
    "page_id": {
      "type": "string",
      "description": "Notion page identifier."
    },
    "include_children": {
      "type": "boolean",
      "description": "When true, include child blocks recursively."
    }
  }
} as const,
  outputSchema: {
  "type": "object",
  "description": "Raw Notion response payload.",
  "additionalProperties": true
} as const,
});
