/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { callMcpTool } from '@magsag/mcp-client';

/**
 * request arguments
 */
export type RequestArgs = {
  /**
   * Target URL.
   */
  url: string;
  /**
   * HTTP method (defaults to GET).
   */
  method?: string;
  /**
   * Optional HTTP headers.
   */
  headers?: {
    [key: string]: string;
  };
  /**
   * Optional request body.
   */
  body?: unknown;
};

/**
 * request result
 */
export type RequestResult = {
  status?: number;
  headers?: {
    [key: string]: string;
  };
  /**
   * Response body (decoded when possible).
   */
  body?: unknown;
  [key: string]: unknown;
};

/**
 * Perform an HTTP request.
 * Fetches web content with optional method, headers, and payload overrides.
 */
export const request = callMcpTool<RequestArgs, RequestResult>({
  serverId: "fetch",
  toolName: "request",
  summary: "Perform an HTTP request.",
  description: "Fetches web content with optional method, headers, and payload overrides.",
  inputSchema: {
  "type": "object",
  "required": [
    "url"
  ],
  "properties": {
    "url": {
      "type": "string",
      "description": "Target URL."
    },
    "method": {
      "type": "string",
      "description": "HTTP method (defaults to GET)."
    },
    "headers": {
      "type": "object",
      "description": "Optional HTTP headers.",
      "additionalProperties": {
        "type": "string"
      }
    },
    "body": {
      "description": "Optional request body."
    }
  }
} as const,
  outputSchema: {
  "type": "object",
  "description": "HTTP response payload.",
  "properties": {
    "status": {
      "type": "integer"
    },
    "headers": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "body": {
      "description": "Response body (decoded when possible)."
    }
  },
  "additionalProperties": true
} as const,
});
