/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { callMcpTool } from '@magsag/mcp-client';

/**
 * retrieve arguments
 */
export type RetrieveArgs = {
  id: string;
};

/**
 * retrieve result
 */
export type RetrieveResult = {
  record?: {
    [key: string]: unknown;
  };
  [key: string]: unknown;
};

/**
 * Retrieve a memory record by id.
 */
export const retrieve = callMcpTool<RetrieveArgs, RetrieveResult>({
  serverId: "memory",
  toolName: "retrieve",
  summary: "Retrieve a memory record by id.",
  inputSchema: {
  "type": "object",
  "required": [
    "id"
  ],
  "properties": {
    "id": {
      "type": "string"
    }
  }
} as const,
  outputSchema: {
  "type": "object",
  "properties": {
    "record": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "additionalProperties": true
} as const,
});
