/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { callMcpTool } from '@magsag/mcp-client';

/**
 * search arguments
 */
export type SearchArgs = {
  query?: string;
  tags?: ReadonlyArray<string>;
  limit?: number;
};

/**
 * search result
 */
export type SearchResult = {
  results?: ReadonlyArray<{
    [key: string]: unknown;
  }>;
  [key: string]: unknown;
};

/**
 * Search memories by text or tags.
 */
export const search = callMcpTool<SearchArgs, SearchResult>({
  serverId: "memory",
  toolName: "search",
  summary: "Search memories by text or tags.",
  inputSchema: {
  "type": "object",
  "properties": {
    "query": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "limit": {
      "type": "integer"
    }
  }
} as const,
  outputSchema: {
  "type": "object",
  "properties": {
    "results": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    }
  },
  "additionalProperties": true
} as const,
});
