/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { callMcpTool } from '@magsag/mcp-client';

/**
 * store arguments
 */
export type StoreArgs = {
  text: string;
  tags?: ReadonlyArray<string>;
  /**
   * ISO timestamp for automatic expiration.
   */
  expires_at?: string;
};

/**
 * store result
 */
export type StoreResult = {
  id?: string;
  [key: string]: unknown;
};

/**
 * Store a memory record.
 * Persists a memory node with optional metadata tags.
 */
export const store = callMcpTool<StoreArgs, StoreResult>({
  serverId: "memory",
  toolName: "store",
  summary: "Store a memory record.",
  description: "Persists a memory node with optional metadata tags.",
  inputSchema: {
  "type": "object",
  "required": [
    "text"
  ],
  "properties": {
    "text": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "expires_at": {
      "type": "string",
      "description": "ISO timestamp for automatic expiration."
    }
  }
} as const,
  outputSchema: {
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    }
  },
  "additionalProperties": true
} as const,
});
