/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { callMcpTool } from '@magsag/mcp-client';

/**
 * list_entries arguments
 */
export type ListEntriesArgs = {
  /**
   * Directory to list (relative).
   */
  path?: string;
};

/**
 * list_entries result
 */
export type ListEntriesResult = {
  entries?: ReadonlyArray<{
    [key: string]: unknown;
  }>;
  [key: string]: unknown;
};

/**
 * List directory entries.
 * Enumerate files and folders at the provided path.
 */
export const listEntries = callMcpTool<ListEntriesArgs, ListEntriesResult>({
  serverId: "filesystem",
  toolName: "list_entries",
  summary: "List directory entries.",
  description: "Enumerate files and folders at the provided path.",
  inputSchema: {
  "type": "object",
  "properties": {
    "path": {
      "type": "string",
      "description": "Directory to list (relative)."
    }
  }
} as const,
  outputSchema: {
  "type": "object",
  "properties": {
    "entries": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    }
  },
  "additionalProperties": true
} as const,
});
