/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { callMcpTool } from '@magsag/mcp-client';

/**
 * read_text arguments
 */
export type ReadTextArgs = {
  /**
   * Relative path to read.
   */
  path: string;
};

/**
 * read_text result
 */
export type ReadTextResult = {
  /**
   * File contents.
   */
  content?: string;
  [key: string]: unknown;
};

/**
 * Read a UTF-8 text file.
 * Reads contents from disk and returns UTF-8 text.
 */
export const readText = callMcpTool<ReadTextArgs, ReadTextResult>({
  serverId: "filesystem",
  toolName: "read_text",
  summary: "Read a UTF-8 text file.",
  description: "Reads contents from disk and returns UTF-8 text.",
  inputSchema: {
  "type": "object",
  "required": [
    "path"
  ],
  "properties": {
    "path": {
      "type": "string",
      "description": "Relative path to read."
    }
  }
} as const,
  outputSchema: {
  "type": "object",
  "properties": {
    "content": {
      "type": "string",
      "description": "File contents."
    }
  },
  "additionalProperties": true
} as const,
});
