/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { callMcpTool } from '@magsag/mcp-client';

/**
 * write_text arguments
 */
export type WriteTextArgs = {
  path: string;
  content: string;
  /**
   * Overwrite existing file when true.
   */
  overwrite?: boolean;
};

/**
 * write_text result
 */
export type WriteTextResult = {
  bytes_written?: number;
  [key: string]: unknown;
};

/**
 * Write UTF-8 text to a file.
 * Writes text content, creating parent directories when necessary.
 */
export const writeText = callMcpTool<WriteTextArgs, WriteTextResult>({
  serverId: "filesystem",
  toolName: "write_text",
  summary: "Write UTF-8 text to a file.",
  description: "Writes text content, creating parent directories when necessary.",
  inputSchema: {
  "type": "object",
  "required": [
    "path",
    "content"
  ],
  "properties": {
    "path": {
      "type": "string"
    },
    "content": {
      "type": "string"
    },
    "overwrite": {
      "type": "boolean",
      "description": "Overwrite existing file when true."
    }
  }
} as const,
  outputSchema: {
  "type": "object",
  "properties": {
    "bytes_written": {
      "type": "integer"
    }
  },
  "additionalProperties": true
} as const,
});
