/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { createPostgresQuery } from '@magsag/mcp-client';

/**
 * query arguments
 */
export type QueryArgs = {
  /**
   * Read-only SQL statement.
   */
  sql: string;
  /**
   * PostgreSQL positional parameters.
   */
  params?: ReadonlyArray<unknown>;
};

/**
 * query result
 */
export type QueryResult = {
  rows?: ReadonlyArray<{
    [key: string]: unknown;
  }>;
  [key: string]: unknown;
};

/**
 * Execute a parameterised read-only SQL query.
 * Provides a safe wrapper for SELECT-style statements against the readonly replica.
 */
export const query = createPostgresQuery<QueryArgs, QueryResult>({
  serverId: "pg-readonly",
  toolName: "query",
  summary: "Execute a parameterised read-only SQL query.",
  description: "Provides a safe wrapper for SELECT-style statements against the readonly replica.",
});
