/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { callMcpTool } from '@magsag/mcp-client';

/**
 * list_issues arguments
 */
export type ListIssuesArgs = {
  /**
   * Repository owner.
   */
  owner: string;
  /**
   * Repository name.
   */
  repo: string;
  /**
   * Filter by issue state (open|closed|all).
   */
  state?: string;
  /**
   * Optional label filters.
   */
  labels?: ReadonlyArray<string>;
};

/**
 * list_issues result
 */
export type ListIssuesResult = ReadonlyArray<{
  [key: string]: unknown;
}>;

/**
 * List repository issues.
 * Enumerate issues for a repository with optional state and label filtering.
 */
export const listIssues = callMcpTool<ListIssuesArgs, ListIssuesResult>({
  serverId: "github",
  toolName: "list_issues",
  summary: "List repository issues.",
  description: "Enumerate issues for a repository with optional state and label filtering.",
  inputSchema: {
  "type": "object",
  "required": [
    "owner",
    "repo"
  ],
  "properties": {
    "owner": {
      "type": "string",
      "description": "Repository owner."
    },
    "repo": {
      "type": "string",
      "description": "Repository name."
    },
    "state": {
      "type": "string",
      "description": "Filter by issue state (open|closed|all)."
    },
    "labels": {
      "type": "array",
      "description": "Optional label filters.",
      "items": {
        "type": "string"
      }
    }
  }
} as const,
  outputSchema: {
  "type": "array",
  "description": "Array of issues matching the query.",
  "items": {
    "type": "object",
    "additionalProperties": true
  }
} as const,
});
