/* eslint-disable */
// ---------------------------------------------------------------------------
// This file is auto-generated by pnpm mcp:codegen. Do not edit manually.
// ---------------------------------------------------------------------------

import { callMcpTool } from '@magsag/mcp-client';

/**
 * sql_select arguments
 */
export type SqlSelectArgs = {
  /**
   * Read-only SQL query.
   */
  sql: string;
  /**
   * Positional query parameters.
   */
  params?: ReadonlyArray<unknown>;
};

/**
 * sql_select result
 */
export type SqlSelectResult = {
  rows?: ReadonlyArray<{
    [key: string]: unknown;
  }>;
  [key: string]: unknown;
};

/**
 * Execute a read-only SQL statement.
 * Runs parameterised SELECT queries against the Supabase Postgres database.
 */
export const sqlSelect = callMcpTool<SqlSelectArgs, SqlSelectResult>({
  serverId: "supabase",
  toolName: "sql_select",
  summary: "Execute a read-only SQL statement.",
  description: "Runs parameterised SELECT queries against the Supabase Postgres database.",
  inputSchema: {
  "type": "object",
  "required": [
    "sql"
  ],
  "properties": {
    "sql": {
      "type": "string",
      "description": "Read-only SQL query."
    },
    "params": {
      "type": "array",
      "description": "Positional query parameters.",
      "items": {
        "description": "Parameter value."
      }
    }
  }
} as const,
  outputSchema: {
  "type": "object",
  "description": "Supabase rows payload.",
  "properties": {
    "rows": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    }
  },
  "additionalProperties": true
} as const,
});
